[package]
name = "caya-desktop-pet"
version = "0.1.0"
description = "CaYaDev temalı masaüstü pet uygulaması"
authors = ["CaYatur"]
edition = "2021"

[lib]
name = "caya_desktop_pet_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.3", features = [] }

[dependencies]
tauri = { version = "2.1.1", features = ["tray-icon"] }
tauri-plugin-fs = "2.0.3"
tauri-plugin-os = "2.0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
windows = { version = "0.61.3", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging"] }

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
